#cloud-config

coreos:
  update:
    reboot-strategy: off
  units:
    - name: oam-decider.service
      command: start
      content: |
        [Unit]
        Description=OpenAerialMap SWF Decider
        After=docker.service

        [Service]
        Restart=always

        ExecStartPre=-/usr/bin/docker kill oam-decider
        ExecStartPre=-/usr/bin/docker rm -f oam-decider
        ExecStartPre=/usr/bin/docker pull quay.io/hotosm/oam-decider:latest
        ExecStart=/usr/bin/docker run --name oam-decider -p 80:8000 quay.io/hotosm/oam-decider:latest
        ExecStop=/usr/bin/docker stop -t 2 oam-decider
